name: Documentation

on:
  push: {}

jobs:
  documentation:
    name: Generate Documentation HTML
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: './'
          doxyfile-path: './Doxyfile'

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: SoecJan/soecjan.github.io
          publish_branch: master
          publish_dir: ./public
