name: Documentation

on:
  push: {}

jobs:
  documentation:
    name: Generate Documentation HTML
    runs-on: ubuntu-18.04
    steps:
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: './'
          doxyfile-path: './'

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
